spring:
  application:
    name: data-gen-oracle-batch
#  batch:
#    job:
#      enabled: true
#    jdbc:
#      initialize-schema: EMBEDDED
#      schema: classpath:org/springframework/batch/core/schema-hsqldb.sql
  datasource:
    username: rixon
    password: oracle
    url: jdbc:oracle:thin:@oracle21c-ol8.localdomain:1521/pdb1
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 50
      minimum-idle: 10
      max-lifetime: 300000
      pool-name: oracle19c
      connection-test-query: select 1 from dual
      data-source-properties:
        "[v$session.program]": batch-tryout-oracle
      idle-timeout: 120000
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    show-sql: false
    hibernate:
      ddl-auto: validate

logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger{36}.%M - %msg%n"
    level:
      - org.hibernate.SQL: error

